### ISSUE TITLE
Question: provisioning

### ISSUE THREAD

**Issue by tartavull** [pinpox/lollypops#17]
Is it possible to use lollypops to create instances in gcp or aws?

**Comment by pinpox** [comment]
It should be possible to add commands that are executed before/after the actual deployment. These could be used for creating the instances. I'm not able to add this feature myself currently, but I'll review any PR's if you want to give it a try

**Comment by cmacrae** [comment]
I just opened #23 which can be used to do this :) In fact I talk about how I'm booting a VM locally for provisioning in the PR description

**Comment by pinpox** [comment]
Thanks @cmacrae!

Closing this as resolved by #23
