### ISSUE TITLE
`deploy-secrets` fails if sudo is used

### ISSUE THREAD

**Issue by pf56** [pinpox/lollypops#18]
Trying to deploy secrets to a host with `sudo` enabled fails with a permissions error.

```
lollypops.deployment = {
  ssh.user = "deploy";
  sudo.enable = true;
};
```

```
[myhost:deploy-secrets] Deploying secrets to: myhost
[myhost:deploy-secrets] Deploying credentials to /var/src/lollypops-secrets/credentials
[myhost:deploy-secrets] bash: line 1: /var/src/lollypops-secrets/credentials: Permission denied
```

I guess this is a regression introduced by f1f865f41ac7b433da0960b44322acb4d196d1a5 in response to #5. The file is now owned by `root:root` with `0700`, meaning shell redirection will fail if the remote user isn't root.

**Comment by pinpox** [comment]
Good catch, thank you for the PR!
