### ISSUE TITLE
Rebuilding on local machine?

### ISSUE THREAD

**Issue by jhakonen** [pinpox/lollypops#29]
How do I rebuild my configuration to my local NixOS laptop?

I have so far used this command to rebuild it:
```
sudo nixos-rebuild switch --flake '.#dellxps13'
```
Now I'm trying to take lollypops into use and I wonder what would be the equivalent with it?

I tried this but lollypops starts fiddling with ssh:
```
$ nix run '.' -- dellxps13
warning: Git tree '/home/jhakonen/nixos-config' is dirty
[dellxps13:deploy-flake] Deploying flake to: dellxps13
[dellxps13:deploy-flake] ssh: connect to host dellxps13 port 22: Connection refused
[dellxps13:deploy-flake] rsync: connection unexpectedly closed (0 bytes received so far) [sender]
[dellxps13:deploy-flake] rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
task: Failed to run task "dellxps13": exit status 255
```
I have set `lollypops.deployment.local-evaluation = true;` but it doesn't seem to have any effect. I don't have ssh server setup on the laptop, so its expected that connect would fail. The flake config is at current working directory, so there shouldn't be any reason to connect anywhere. Do I need some extra configuration to get this working?

**Comment by pinpox** [comment]
Hello :wave:,
lollypops expects an SSH server running and treats localhost as any other host. If you don't want to expose your laptop via ssh, you can configure it to only accept connections on port 22 at the `127.0.0.1` address.

`local-evaluation` causes nixos-rebuild to evaluate locally, but the `--target-host` is stil reached via SSH. Also the copying operation is done via rsync over ssh.

**Comment by pinpox** [comment]
>  Would it make sense have some custom command that would allow running commands on the remote host, e.g. remote-run reboot that would be exposed to the task cmds?
> Also exposing something like e.g. the flake's path#config as a variable would be useful.

I'm open to review PR's on this if you want to give it a go. I think that is a separate issue though, so I'll close this one as the original question seems fixed
