### ISSUE TITLE
Support `boot`, `test` and `dry-activate` actions

### ISSUE THREAD

**Issue by misuzu** [pinpox/lollypops#4]
Maybe also add ability to pass flags like `--use-remote-sudo` while at it.
Relevant code: https://github.com/pinpox/lollypops/blob/ad2d9b9504fefbcabfe92c734d80f2f3a5e3b69e/flake.nix#L95

**Comment by pinpox** [comment]
@misuzu Would it make sense to have the `test` and `dry-activate` and `boot/reboot` actions as *additional* step in the deployment or *instead* of a `switch`? Both is possible without much hassle, I'm thinking about what would be more useful?

**Comment by pinpox** [comment]
I created a pull-request making the action configurable, let me know if that addresses your use case.

**Comment by misuzu** [comment]
> @misuzu Would it make sense to have the `test` and `dry-activate` and `boot/reboot` actions as _additional_ step in the deployment or _instead_ of a `switch`? Both is possible without much hassle, I'm thinking about what would be more useful?

Additional step would probably be redundant. It makes sense to, for example, run only `dry-activate`, to test that deployment is configured properly without actually deploying, or run only `boot` action with subsequent `reboot` command, without switching running system.

**Comment by pinpox** [comment]
Implemented and documented using env vars. Feel free to reopen if I missed something.
