### ISSUE TITLE
Ability deploy to all hosts at once

### ISSUE THREAD

**Issue by misuzu** [pinpox/lollypops#8]
Currently it's required to list all hostnames by hand to deploy to all hosts, but what if there's 10 or 50 or even 100 hosts in the configuration?

While it's possible to write something like `nix run . -- $(nix run . -- --list-all  | awk -F: '{ print $1 }' | awk '{ print $2 }' | uniq)`, maybe it's possible to have a more user-friendly way to achieve this?

**Comment by pinpox** [comment]
Thanks for the idea, very useful! I've added a `all` task which will run all hosts.
